### PR TITLE
updated R session for HPC school 2018

### PR DESCRIPTION
**Pull request by ginolhac**

### CODE REVIEW

**Comment by ginolhac** [comment]
the conflicted files could be overwritten with the new ones

**Comment by Falkor** [comment]
We have changed the layout -- now your tuto is primarily hosted in `maths/R`.
Can you first add a new commit operating this move (`git mv advanced/R maths/R`) before I merge ?  It will facilitate the integration.

**Comment by Falkor** [comment]
If you can also, update the main README to match the template for all tutos (with the badges etc. ) see https://github.com/ULHPC/tutorials/blob/devel/docs/contributing.md#new-tutorial-layout

**Comment by ginolhac** [comment]
Ok thanks. I missed that. I should have pulled all that before :(
here is a new attempt

**Comment by ginolhac** [comment]
Ok I missed that info. Sorry, I should have pulled your branch before.
Here is a new attempt

**Pull request merged**
